# Generated by Django 3.2.5 on 2021-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='dump_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='fat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='stupid_count',
            field=models.IntegerField(default=0),
        ),
    ]
